config/routes.rb
SapphoCurrentCost::Application.routes.draw do
  post "administrator/login"

  post "administrator/logout"

  get "presentation/index"

  resources :devices

  resources :samples

  root :to => 'presentation#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :samples, :dependent => :destroy
  validates :description, :upload_code, :presence => true, :uniqueness => true
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :device
  validates_presence_of :device, :message => 'has not been defined'
  validates :sample_time, :power, :temperature, :presence => true
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  def login
    session[:loggedIn] = true if Digest::SHA1.hexdigest(params[:password]) == SapphoCurrentCost::Application.config.admin_password_hash
    redirect_to request.referer
  end
  def logout
    session[:loggedIn] = false
    redirect_to request.referer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    if logged_in
      @devices = Device.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @devices }
      end
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    if logged_in
      @device = Device.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @device }
      end
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    if logged_in
      @device = Device.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @device }
      end
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id]) if logged_in
  end

  # POST /devices
  # POST /devices.json
  def create
    if logged_in
      @device = Device.new(params[:device])
      respond_to do |format|
        if @device.save
          format.html { redirect_to @device, :notice => 'Device was successfully created.' }
          format.json { render :json => @device, :status => :created, :location => @device }
        else
          format.html { render :action => "new" }
          format.json { render :json => @device.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    if logged_in
      @device = Device.find(params[:id])
      respond_to do |format|
        if @device.update_attributes(params[:device])
          format.html { redirect_to @device, :notice => 'Device was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @device.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    if logged_in
      @device = Device.find(params[:id])
      @device.destroy
      respond_to do |format|
        format.html { redirect_to devices_url }
        format.json { head :no_content }
      end
    end
  end

  private

  def logged_in
    respond_to do |format|
      format.html { redirect_to root_path, :notice => 'Access denied.' }
      format.json { render :json => {}, :status => :unauthorized }
    end unless session[:loggedIn]
    session[:loggedIn]
  end
end

app/controllers/presentation_controller.rb
class PresentationController < ApplicationController
  def index
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # POST /samples
  # POST /samples.json
  def create
    respond_to do |format|
      sample = params[:sample]
      uploadCode = sample[:upload_code]
      devices = Device.where :upload_code => uploadCode
      if devices.size == 1
        sample[:device_id] = devices[0].id
        sample.delete :upload_code
        @sample = Sample.new(sample)
        if @sample.save
          format.json { render :json => @sample, :status => :created, :location => @sample }
        else
          format.json { render :json => @sample.errors, :status => :unprocessable_entity }
        end
      else
        format.json { render :json => { :upload_code => uploadCode }, :status => :unauthorized }
      end
      format.html { redirect_to root_path }
    end
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
    <div class="field">
      <%= f.label :upload_code %><br />
      <%= f.text_field :upload_code %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Upload Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.description %></td>
    <td><%= device.upload_code %></td>
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @device.description %>
</p>

<p>
  <b>Upload code:</b>
  <%= @device.upload_code %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SapphoCurrentCost</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='user_panel'>
  <% unless session[:loggedIn] %>
    <%= form_tag '/administrator/login' do -%>
      <%= label_tag 'password' %>
      <%= text_field_tag 'password' %>
      <%= submit_tag 'Login' %>
    <% end -%>
  <% else %>
      <%= form_tag '/administrator/logout' do -%>
        <%= label_tag 'You are logged in' %>
        <%= submit_tag 'Logout' %>
      <% end -%>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/presentation/index.html.erb
<h1>Presentation#index</h1>
<p>Find me in app/views/presentation/index.html.erb</p>